
language: cpp
sudo: required
services: ['docker']

script: scons

compiler:
 - clang

matrix:
 allow_failures:
  - os: linux
 include:
  - os: linux
    sudo: required
    dist: trusty
  - os: osx

install:
 - ./.travis-install-deps.sh

branches:
 except:
  - legacy-win32
